export const EGYPT_GOVERNORATES = [
  { en: 'Cairo', ar: 'القاهرة' },
  { en: 'Giza', ar: 'الجيزة' },
  { en: 'Alexandria', ar: 'الإسكندرية' },
  { en: 'Dakahlia', ar: 'الدقهلية' },
  { en: 'Red Sea', ar: 'البحر الأحمر' },
  { en: 'Beheira', ar: 'البحيرة' },
  { en: 'Faiyum', ar: 'الفيوم' },
  { en: 'Gharbia', ar: 'الغربية' },
  { en: 'Ismailia', ar: 'الإسماعيلية' },
  { en: 'Monufia', ar: 'المنوفية' },
  { en: 'Minya', ar: 'المنيا' },
  { en: 'Qalyubia', ar: 'القليوبية' },
  { en: 'New Valley', ar: 'الوادي الجديد' },
  { en: 'Suez', ar: 'السويس' },
  { en: 'Aswan', ar: 'أسوان' },
  { en: 'Asyut', ar: 'أسيوط' },
  { en: 'Beni Suef', ar: 'بني سويف' },
  { en: 'Port Said', ar: 'بورسعيد' },
  { en: 'Damietta', ar: 'دمياط' },
  { en: 'Sharqia', ar: 'الشرقية' },
  { en: 'South Sinai', ar: 'جنوب سيناء' },
  { en: 'Kafr El Sheikh', ar: 'كفر الشيخ' },
  { en: 'Matrouh', ar: 'مطروح' },
  { en: 'Luxor', ar: 'الأقصر' },
  { en: 'Qena', ar: 'قنا' },
  { en: 'North Sinai', ar: 'شمال سيناء' },
  { en: 'Sohag', ar: 'سوهاج' }
];

export const JOB_CATEGORIES = [
  { en: 'Sales & Retail', ar: 'المبيعات والتجزئة' },
  { en: 'Information Technology (IT)', ar: 'تكنولوجيا المعلومات (IT)' },
  { en: 'Customer Service', ar: 'خدمة العملاء' },
  { en: 'Engineering', ar: 'الهندسة' },
  { en: 'Accounting & Finance', ar: 'المحاسبة والمالية' },
  { en: 'Marketing & PR', ar: 'التسويق والعلاقات العامة' },
  { en: 'Human Resources (HR)', ar: 'الموارد البشرية (HR)' },
  { en: 'Management & Consulting', ar: 'الإدارة والاستشارات' },
  { en: 'Healthcare & Medical', ar: 'الرعاية الصحية والطبية' },
  { en: 'Education & Training', ar: 'التعليم والتدريب' },
  { en: 'Logistics & Supply Chain', ar: 'اللوجستيات وسلاسل الإمداد' },
  { en: 'Design, Art & Multimedia', ar: 'التصميم والفنون والوسائط المتعددة' },
  { en: 'Media & Journalism', ar: 'الإعلام والصحافة' },
  { en: 'Hospitality & Tourism', ar: 'الضيافة والسياحة' },
  { en: 'Legal', ar: 'القانون والمحاماة' },
  { en: 'Construction & Real Estate', ar: 'المقاولات والعقارات' },
  { en: 'Manufacturing & Production', ar: 'التصنيع والإنتاج' },
  { en: 'Other', ar: 'أخرى (Other)' }
];
