-- WAZAFLY production bootstrap and upload fix
-- Run once in the Supabase SQL Editor. Safe to re-run.

-- 1) AI provider table required by /api/ai/proxy and the admin AI screen.
CREATE TABLE IF NOT EXISTS public.ai_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  base_url TEXT NOT NULL,
  model TEXT NOT NULL,
  api_key TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.ai_providers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can manage ai_providers" ON public.ai_providers;
CREATE POLICY "Admins can manage ai_providers" ON public.ai_providers
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin'));

-- 2) Storage bucket and least-privilege policies for CV Bank uploads.
INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Resumes are publicly accessible" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users upload resumes" ON storage.objects;
DROP POLICY IF EXISTS "Users update own resumes" ON storage.objects;
DROP POLICY IF EXISTS "Users delete own resumes" ON storage.objects;

CREATE POLICY "Resumes are publicly accessible" ON storage.objects
  FOR SELECT USING (bucket_id = 'resumes');
CREATE POLICY "Authenticated users upload resumes" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'resumes' AND owner_id = auth.uid());
CREATE POLICY "Users update own resumes" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'resumes' AND owner_id = auth.uid())
  WITH CHECK (bucket_id = 'resumes' AND owner_id = auth.uid());
CREATE POLICY "Users delete own resumes" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'resumes' AND owner_id = auth.uid());

-- 3) Add Dahl in the Admin UI after this SQL runs:
-- Admin Dashboard > AI Providers > Add provider
-- Name: Dahl (Kimi K2.6)
-- Base URL: https://inference.dahl.global/v1
-- Model: moonshotai/Kimi-K2.6
-- API key: paste the key there and make it active.
-- Do not put the API key into frontend code or git.
